export const ProjectDetails = [
  {
    id: 1,
    Name: "Voice Enabled E-commerce App",
    imgLink: "assets/images/Shoopers.png",
    siteLink: "https://shoopersloop.herokuapp.com/",
    githubLink: "https://github.com/Nikhil-Duttaroy/ShoopersLoop",
  },
  {
    id: 2,
    Name: "TextCollabo",
    imgLink: "assets/images/Shoopers.png",
    siteLink: "https://shoopersloop.herokuapp.com/",
    githubLink: "https://github.com/Nikhil-Duttaroy/ShoopersLoop",
  },
  {
    id: 3,
    Name: "Youtube Clone",
    imgLink: "assets/images/Youtube.png",
    siteLink: "https://reactytclone.web.app/login",
    githubLink: "https://github.com/Nikhil-Duttaroy/Youtube-Clone",
  },
  {
    id: 4,
    Name: "Quiz IT WebApp",
    imgLink: "assets/images/QuizIT.png",
    siteLink: "https://intpprojectquizit.000webhostapp.com/QuizIT/",
    githubLink: "https://github.com/Nikhil-Duttaroy/QuizIT",
  },
  {
    id: 5,
    Name: "React Contact Manager",
    imgLink: "assets/images/basic.png",
    siteLink: "https://simple-portfolio-design.netlify.app",
    githubLink: "https://github.com/Nikhil-Duttaroy/Basic-Portfolio",
  },
  {
    id: 6,
    Name: "Basic Portfolio Design",
    imgLink: "assets/images/basic.png",
    siteLink: "https://simple-portfolio-design.netlify.app",
    githubLink: "https://github.com/Nikhil-Duttaroy/Basic-Portfolio",
  },
  {
    id: 7,
    Name: "LivSpace",
    imgLink: "assets/images/Livspace.png",
    siteLink: "https://livspace-clone.netlify.app",
    githubLink: "https://github.com/Nikhil-Duttaroy/Livspace",
  },
];